---
name: Validate

"on":
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *" # Daily at midnight

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  validate:
    permissions:
      contents: write # Required by test_val for coverage badge gist update
      pull-requests: write # Required by test_val for PR comments
    # Branch @main
    uses: PlayFaster/.github/.github/workflows/validate.yaml@cc6a1a12a5c7bc831fdda2bd385a3221112a7937
    with:
      component_name: huawei_router_5g
      gist_id: b5cb47f2b37e140da07eefd17ac19721
    secrets:
      GIST_SECRET: ${{ secrets.GIST_SECRET }}
